services:
  medispeak_db:
    image: 'postgres:${POSTGRES_IMAGE_TAG:?}'
    container_name: medispeak_db
    volumes:
      - medispeak_data:/var/lib/postgresql/data:rw
    command: postgres -c 'max_connections=500'
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT}:5432"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 30s
      timeout: 10s
      retries: 5

  medispeak_backend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        RAILS_ENV: ${RAILS_ENV}
        BUNDLE_DEPLOYMENT: ${BUNDLE_DEPLOYMENT}
        BUNDLE_PATH: ${BUNDLE_PATH}
        BUNDLE_WITHOUT: ${BUNDLE_WITHOUT}
    container_name: medispeak_backend
    command: "bundle exec rails s -p ${BACKEND_PORT} -b '0.0.0.0'"
    environment:
      DB_HOST: medispeak_db
      DB_NAME: ${DB_NAME}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      OPENAI_ACCESS_TOKEN: ${OPENAI_ACCESS_TOKEN}
      OPENAI_ORGANIZATION_ID: ${OPENAI_ORGANIZATION_ID}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_REGION: ${AWS_REGION}
      AWS_BUCKET: ${AWS_BUCKET}
      PLUGIN_BASE_URL: ${PLUGIN_BASE_URL}
    volumes:
      - .:/app:cached
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
    depends_on:
      medispeak_db:
        condition: service_healthy
    restart: unless-stopped
volumes:
  medispeak_data:
    driver: local
